services:
  postgres:
    image: postgres:15
    container_name: ompay-db
    restart: always
    environment:
      POSTGRES_USER: ompay
      POSTGRES_PASSWORD: ompaypass
      POSTGRES_DB: ompaydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ompay-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  backend:
    image: ua-ompay-registry.gos.orange.com/ompay/api:0.0.1
    container_name: ompay-api
    restart: always
    ports:
      - '3002:3001'
    environment:
      DATABASE_URL: postgres://ompay:ompaypass@postgres:5432/ompaydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .env:/app/.env

volumes:
  postgres-data:
  redis-data:
