

services:
  postgres:
    image: postgres:15
    container_name: ompay-db
    restart: always
    environment:
      POSTGRES_USER: ompay
      POSTGRES_PASSWORD: ompaypass
      POSTGRES_DB: ompaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ompay-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    container_name: ompay-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://ompay:ompaypass@postgres:5432/ompaydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
  redis-data:
